server.port=${PORT:8080}

spring.datasource.url=${PROD_DB_URL}
spring.datasource.username=${PROD_DB_USERNAME}
spring.datasource.password=${PROD_DB_PASSWORD}

spring.mail.username=${PROD_MAIL_USERNAME}
spring.mail.password=${PROD_MAIL_PASSWORD}

spring.security.oauth2.client.registration.google.client-id=${PROD_GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${PROD_GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
app.frontend.oauth2-success-url=${APP_FRONTEND_OAUTH2_SUCCESS_URL:http://localhost:5173/auth/oauth2/success}
app.jwt.secret=${PROD_JWT_SECRET}
app.backend-base-url=${PROD_BACKEND_BASE_URL}

server.servlet.session.cookie.name=SCIPUB_SESSION_PROD
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=none

app.cors.allowed-origins=${PROD_CORS_ALLOWED_ORIGINS}

app.auth.refresh-cookie-secure=true
app.auth.refresh-cookie-same-site=None

logging.level.root=INFO
logging.level.com.brotherhood.scipubtts=INFO
logging.level.org.springframework.security=WARN